name: 'Create build artifact'
on: workflow_dispatch

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: 'install dependencies'
      run: npm install
    - name: 'build'
      run: npm run build:zip
    - uses: actions/upload-artifact@v2
      with:
        name: refined-whatsapp.zip
        path: refined-whatsapp.zip
